--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XanderID-MC/XPluginLoader
build-by-default: true
branches:
- main
projects:
  XPluginLoader:
    path: ""
    icon: "icon.png"
    lint: false
...
